sudo: required

language: php

services:
  - docker

before_install:
  - docker-compose up -d --build
  - cp backend/.env.example backend/.env
  - docker-compose exec app composer install
  - docker-compose exec app php artisan key:generate

  # - docker-compose exec db chown -R mysql:mysql /var/run/mysqld/mysqld.sock
  # - docker-compose exec db chmod -R 644 /var/run/mysqld/mysqld.sock
  - docker-compose exec db mysql services mysql start
  - docker-compose exec db create database test_books | mysql -uroot -psecret
  - docker-compose exec app php artisan migrate:fresh --database=mysql_testing

script:
  - docker-compose exec app ./vendor/bin/phpunit

after_success:
  - echo "DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin

  - docker push soysan/laravel-book
