sude: required

language: php

services:
    - docker

before_install:
    - docker-compose up -d --build
    - ls -a backend
    - cp backend/.env.example backend/.env
    - php artisan key:generate

script:
    - docker-compose exec app ./vender/bin/phpunit

after_success:
    - echo "DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin

    - docker push soysan/laravel-book
